entrypoints:
  - id: http
    addr: '[::]:8080'
    tls: false

  - id: https
    addr: '[::]:8443'
    tls: true

routes:
  #  - host: m4rc3l.de
  #    middlewares: [ ]
  - host: localhost
    entrypoints: [ http ]
    service: python

  - host: www.google.com
    entrypoints: [ http ]
    service: google

  - host: git.m4rc3l.de
    entrypoints: [ http, https ]
    middlewares: [ ]
    service: git

  - host: ci.m4rc3l.de
    entrypoints: [ http, https ]
    middlewares: [ ]
    service: ci

services:
  proxy:
    - id: git
      upstream: git
    - id: ci
      upstream: ci
    - id: google
      upstream: google
    - id: python
      upstream: python

  static:
    - id: m4rc3l
      root: /var/www/html
      index: index.html
      fallback: 404.html

upstreams:
  - id: git
    addrs: [ 10.99.0.26:8443 ]
    sni: marcel.hel1.not4y.net

  - id: ci
    addrs: [ 10.99.0.26:8443 ]
    sni: marcel.hel1.not4y.net

  - id: google
    addrs: [ 142.250.180.68:443 ]
    sni: www.google.com

  - id: python
    addrs: [ 127.0.0.1:8000 ]

